### ISSUE TITLE
Vol /mnt/usb/ is mounted randomly

### ISSUE THREAD

**Issue by jheredianet** [mluggy/teslabox#27]
Hi, 
Is this behaviour correct while teslabox is connected to the car?

If you use this command:   
`find /mnt/usb/`

Sometimes you see the contents of the folder TeslaCam, then they desapear and appear again as you see in the following screenshot

![image](https://github.com/mluggy/teslabox/assets/45735191/42859e63-c2b7-4075-9254-79ab53d51fc4)

**Comment by mluggy** [comment]
yes, this is because teslabox remounts (mounts and unmounts) every seconds to get a hold of new files.
if you want to mount manually run ```service teslabox stop``` and mount /mnt/usb but you will not see new files (if they are still written by the car) until you remount.

you normally don't need to SSH the box unless you want the originals, and there's a feature I'm working on to let you retrieve them from the archives list.

**Comment by jheredianet** [comment]
I see. Thank you.
